# Generated by Django 3.0.8 on 2020-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20200901_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbanner',
            name='url',
            field=models.CharField(max_length=50, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mbanner',
            name='url',
            field=models.CharField(max_length=50, verbose_name='URL'),
        ),
    ]
