# Generated by Django 3.0.8 on 2020-09-01 13:24

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20200901_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbanner',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '280x176', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка баннера'),
        ),
    ]
