# Generated by Django 3.0.8 on 2020-09-01 13:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('banners', '0006_auto_20200901_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigbanner',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='mbanner',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Темы'),
        ),
    ]
