# Generated by Django 3.0.8 on 2020-09-22 13:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200906_2223'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('news', '0003_auto_20200921_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='menu',
            field=mptt.fields.TreeOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu', verbose_name='Пункт меню'),
        ),
        migrations.CreateModel(
            name='TaggedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_taggednews_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
