# Generated by Django 3.0.8 on 2020-09-09 11:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0009_auto_20200906_2223'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('keywords', models.CharField(help_text='Введите ключевые слова для SEO через запятую!', max_length=500, verbose_name='Ключевые слова')),
                ('seo_description', models.CharField(help_text='SEO описание новости. Не более 500 символов', max_length=500, verbose_name='SEO описание')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifed', models.DateTimeField(auto_now=True)),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение новости')),
                ('min_free_cropping', image_cropping.fields.ImageRatioField('image', '200x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка фото')),
                ('list_img_cropping', image_cropping.fields.ImageRatioField('image', '4x3', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='list img cropping')),
                ('top_news_cropping', image_cropping.fields.ImageRatioField('image', '16x9', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='top news cropping')),
                ('image_in_body', models.BooleanField(default=False, verbose_name='Вставить изображение в материал')),
                ('topNews', models.BooleanField(default=False, verbose_name='В главные новости')),
                ('news_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('publisdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Category', verbose_name='Категория')),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu', verbose_name='Пункт меню')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
