# Generated by Django 3.0.8 on 2020-09-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commision',
            name='members',
            field=models.ManyToManyField(related_name='depmembers', to='sovet.deputat', verbose_name='Члены комисии'),
        ),
        migrations.AlterField(
            model_name='commision',
            name='chairman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depchairman', to='sovet.deputat', verbose_name='Председатель комиссии'),
        ),
    ]
