# Generated by Django 3.0.8 on 2020-10-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apperal',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reception.recipient', verbose_name='Адресат обращения'),
            preserve_default=False,
        ),
    ]
