# Generated by Django 3.0.8 on 2020-10-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_apperal_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['id'], 'verbose_name': 'Тема обращения', 'verbose_name_plural': 'Темы обращения'},
        ),
        migrations.AlterField(
            model_name='apperal',
            name='theme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='reception.theme', verbose_name='Тема обращения'),
        ),
    ]
