# Generated by Django 3.0.8 on 2020-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20201013_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail рассылки'),
        ),
    ]
