# Generated by Django 3.0.8 on 2020-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200831_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_in_body',
            field=models.BooleanField(default=False, verbose_name='Вставить изображение в материал'),
        ),
    ]
