# Generated by Django 3.0.8 on 2020-08-31 16:24

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_news_min_free_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='list_img_cropping',
            field=image_cropping.fields.ImageRatioField('image', '360x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='list img cropping'),
        ),
        migrations.AddField(
            model_name='news',
            name='top_news_cropping',
            field=image_cropping.fields.ImageRatioField('image', '220x160', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='top news cropping'),
        ),
        migrations.AlterField(
            model_name='news',
            name='min_free_cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка фото'),
        ),
    ]
