# Generated by Django 3.0.8 on 2020-08-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200901_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsauthor',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Наименование органа'),
            preserve_default=False,
        ),
    ]
