# Generated by Django 3.0.8 on 2020-08-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_docsauthor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=700, verbose_name='Название'),
        ),
    ]
