# Generated by Django 3.0.8 on 2020-09-25 17:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20200925_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='DocCategory',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.DocCategory', verbose_name='Категория'),
        ),
    ]
