# Generated by Django 3.0.8 on 2020-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20200925_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(max_length=700, unique=True, verbose_name='URL'),
        ),
    ]
