# Generated by Django 3.0.8 on 2020-08-31 09:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Пункт меню')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.Menu', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Главное меню',
            },
        ),
    ]
