# Generated by Django 3.0.8 on 2020-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_footermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermenu',
            name='weight',
            field=models.IntegerField(default=1, help_text='Вес определяет положение ссылки в выводе меню. Более легкие ссылки будут наверху', verbose_name='Вес ссылки'),
            preserve_default=False,
        ),
    ]
