# Generated by Django 3.0.8 on 2020-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_footermenu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
