# Generated by Django 3.0.8 on 2020-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200906_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=256, verbose_name='URL')),
                ('linkClass', models.CharField(help_text='Классы можно искать на сайте https://fontawesome.ru/all-icons/', max_length=50, verbose_name='Класс значка fontawesome')),
                ('color', models.CharField(default='#0057c1', max_length=7, verbose_name='Цвет знача при наведении')),
                ('active', models.BooleanField(verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Значок соцсети',
                'verbose_name_plural': 'Значки соцсетей',
            },
        ),
    ]
