# Generated by Django 3.0.8 on 2020-09-01 10:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, verbose_name='Заголовок')),
                ('keywords', models.CharField(help_text='Введите ключевые слова для SEO через запятую!', max_length=500, verbose_name='Ключевые слова')),
                ('seo_description', models.CharField(help_text='SEO описание новости. Не более 500 символов', max_length=500, verbose_name='SEO описание')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifed', models.DateTimeField(auto_now=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст страницы')),
                ('publisdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu', verbose_name='Пункт меню')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Старницы',
            },
        ),
    ]
