# Generated by Django 3.0.8 on 2020-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplepage', '0002_auto_20200901_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='title_in_block',
            field=models.BooleanField(default=False, verbose_name='Отображать название блока'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='key',
            field=models.CharField(help_text='Ключ только на английском языке', max_length=50, unique=True, verbose_name='Ключ блока'),
        ),
    ]
