# Generated by Django 3.0.8 on 2020-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplepage', '0005_auto_20200921_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-publisdDate'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
