# Generated by Django 3.0.8 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20201019_1824'),
        ('simplepage', '0007_page_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='docs',
            field=models.ManyToManyField(blank=True, null=True, to='documents.Documents', verbose_name='Документы'),
        ),
    ]
