# Generated by Django 3.0.8 on 2020-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_adddocs'),
        ('simplepage', '0008_page_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='docs',
            field=models.ManyToManyField(blank=True, to='documents.Documents', verbose_name='Документы'),
        ),
    ]
