# Generated by Django 3.0.8 on 2020-10-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200921_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemup',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='typemup',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
