# Generated by Django 3.0.8 on 2020-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201021_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmup',
            name='shortTitle',
            field=models.CharField(max_length=500, unique=True, verbose_name='Сокращенное назвение'),
        ),
        migrations.AlterField(
            model_name='listmup',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Официальное полное название'),
        ),
    ]
