# Generated by Django 3.0.8 on 2020-10-04 20:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0002_auto_20200924_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputat',
            name='vicechairman',
            field=models.BooleanField(default=False, help_text='Заместителем председателя Совета может быть только один депутат.', verbose_name='Заместитель председателя Совета'),
        ),
        migrations.AlterField(
            model_name='deputat',
            name='grafic',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Место и время приёма'),
        ),
    ]
