# Generated by Django 3.0.8 on 2020-10-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0003_auto_20201004_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okrug',
            options={'ordering': ['title'], 'verbose_name': 'Округ', 'verbose_name_plural': 'Округа'},
        ),
    ]
