# Generated by Django 3.0.8 on 2020-09-24 14:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='func',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Полномочия, задачи, фукнции'),
            preserve_default=False,
        ),
    ]
