# Generated by Django 3.0.8 on 2020-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200906_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
