# Generated by Django 3.0.8 on 2020-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_allsitesmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsitesmenu',
            options={'verbose_name': 'Полезный сайт', 'verbose_name_plural': 'Полезные сайты'},
        ),
        migrations.RemoveField(
            model_name='allsitesmenu',
            name='slug',
        ),
        migrations.AddField(
            model_name='allsitesmenu',
            name='url',
            field=models.CharField(default='http://yandex.ru/', max_length=300, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
