# Generated by Django 3.0.8 on 2020-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplepage', '0003_auto_20200901_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='blockclass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс div текстовго блока'),
        ),
    ]
