# Generated by Django 3.0.8 on 2020-08-31 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('documents', '0003_auto_20200831_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.CharField(help_text='Введите ключевые слова для SEO через запятую!', max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='news',
            name='seo_description',
            field=models.CharField(help_text='SEO описание новости. Не более 500 символов', max_length=500, verbose_name='SEO описание'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('keywords', models.CharField(help_text='Введите ключевые слова для SEO через запятую!', max_length=500, verbose_name='Ключевые слова')),
                ('seo_description', models.CharField(max_length=500, verbose_name='SEO описание')),
                ('number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('docDate', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('descrpition', models.TextField(verbose_name='Описание ')),
                ('publisdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
