# Generated by Django 3.0.8 on 2020-08-31 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20200831_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsauthor',
            options={'verbose_name': 'Орган принявший документ', 'verbose_name_plural': 'Органы принимающие документы'},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='category',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='tags',
        ),
        migrations.AddField(
            model_name='documents',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.DocsAuthor', verbose_name='Орган, принявший документ'),
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/documents', verbose_name='Документ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='descrpition',
            field=models.TextField(blank=True, null=True, verbose_name='Описание документа'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='docDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата подписания документа'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер документа'),
        ),
    ]
