# Generated by Django 3.0.8 on 2020-09-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20200901_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
