# Generated by Django 3.0.8 on 2020-09-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200909_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тип документа')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип документов',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='publisdDate',
            new_name='publishDate',
        ),
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='documents',
            name='TypeDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.DocType', verbose_name='Тип документа'),
        ),
    ]
