# Generated by Django 3.0.8 on 2020-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20200917_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(max_length=700, unique=True, verbose_name='URL'),
        ),
    ]
