# Generated by Django 3.0.8 on 2020-09-25 17:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200906_2223'),
        ('documents', '0018_auto_20200925_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=250, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', mptt.fields.TreeOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu', verbose_name='Пункт меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.DocCategory', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Кагеории докуентов',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='DocCategory',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocCategory', verbose_name='Категория'),
        ),
    ]
