# Generated by Django 3.0.8 on 2020-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20200901_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbanner',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mbanner',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL'),
        ),
    ]
